language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
branches:
  only:
  - gh-pages
  - "/pages-(.*)/"
sudo: false
env:
  secure: vogTZHIYvm67SRobPuqthpHYvLSKd6yxqmidMU09d4FGm0y/OkMCLaHiZ+JJ9jhfl4Pmvh16ETnZAsXEuUiNLs2gX3b/APwMpAfujJ5evwg5RF8g76J1xjK1P6H77m1HY2HEZyeZymglb4PaiBZZRsqGQLd59BtRH8Ul9cIOIewoCxXQUvYH1BVLZz2MonuzsVrzDB+bT4DG9EPAW41zX6sPQVN3w7C5VACuHRAjZ5pjVNEQNoQc5QM1BcR/cFkqnDb1qZpEqCvUcbP6Sr41BHUCutPKjB/BLOHUqSclBJzLgsONbtg+yKLB/4lQjPAIOuzeLspngl+pwAqmQDsdq5TDyZgsZrdGILVZFnHdoGA0rPwr3WV4t4Dz8isW+0JLKWVDdPFLOq+xhuYW2bYPuhIWas5wGEyxoiQALQ6fCpkPMmRbOqjiKFIfxpKD+Pa0HHvX/EfBaTXS2rgNPY6Wp8md/xsJ+AhtSoEdkZ6ZSfYnknpIgU/CBvVo2NC2EPMyYmqPFGUxKKwehMgNYIbc+mrdpwPOo18ZADvFDQL1g+HnJD1s+ltdkddfr3hN7gKoK7aCC0hEdKvK6x8esAOCfqCqtcT19vX6UHMzHCzI0dGEFfS3S24/RsIJJBEj0miwv+0WlE06OTTuE0b9i3EANtT0iXGSVS2aEb8HZoc77AY=
