# Build settings
# Gems
plugins:
- jekyll-paginate
- jekyll-feed

# Site Settings
locale                   : "en-US"
title                    : "Tyler Staut"
title_separator          : "-"
name                     : "Tyler Staut"
description              : ""
url                      : https://Tyler-Staut.github.io
baseurl                  : # The subpath of your site, e.g. "/blog"
repository               : https://github.com/Tyler-Staut/Tyler-Staut.github.io/



# Default keywords (used if no keywords are specified on a page basis)
keywords:

# Short description of your site
desc: Tyler Staut's Portfolio

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
  Home: ""
  About Me: "aboutme"
  # Skills: "skills"
  # Research: "research"
  # Interests: "interests"
  Clubs: "clubs"
  Fold with Me: "foldathome"
  Train an AI: "ai"

# --- Footer options --- #

# If the values are empty, they are ignored
profile:
  name: Tyler Staut
  email: Staut_Tyler@ColumbusState.edu
  facebook: # your-fb-id
  github: Tyler-Staut
  twitter:
  linkedin: tyler-staut-361736121 # your-linkedin-id
  stackoverflow: # your-stackoverflow-id

# To display link in the footer section
pretty-url: "https://github.com/Tyler-Staut"

# --- Misc --- #

# Your Disqus profile (shortname) settings
# disqus: "Your-Disqus-Id"

# Google Analytics Settings
google_analytics: "UA-48101562"

# Set these options as you need (For more information, check Jekyll's site)
# timezone: "Europe/Berlin"
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5


created-by: Tyler Staut
creator-url: https://github.com/Tyler-Staut

# Exclude these files from production site
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
