# Site
repository: tyler-staut/tyler-staut.github.io
# favicon: images/favicon.ico

# Personal info
name: Tyler Staut
title: Full Time Student - Developer - Student Assistant
email: Tyler.R.Staut@gmail.com
website:

# Social links
# twitter_username:
github_username: tyler-staut
# dribbble_username:
facebook_username: tyler.mainframe
# flickr_username:
# instagram_username:
linkedin_username: tyler-staut-361736121
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Tyler Staut. I'm currently a student at Columbus State University, working towards a bachelor's degree in Computer Science. Over the course of my education, I've gained relative proficiency with multiple programming languages. I've also gained a working knowledge of computer networks as well as computer and network security. My topics of particular interest include computer networks and security, and software/hardware development.


# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# Education Section
skills_title: Professional Copentiencies

# Education Section
location_title: Location


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks, software engineering, and Mainframes, some of my other interests and hobbies are:
   - Compentitions (Mathematics and Cyber Security Related)
   - Gaming (Currently play Overwatch)
   - Board Games
   - Electrical Engineering

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
